@extends('layouts.sidebar')
@section('title', 'Mentor Upgrade Assessment')
@section('breadcrumbs')
  <span style="opacity:0.5">›</span>
  <a href="{{ route('upgrade.show') }}" style="color:var(--blue-500);text-decoration:none">Upgrade to Mentor</a>
  <span style="opacity:0.5">›</span> Knowledge Assessment
@endsection

@section('page-content')
<div style="max-width:680px;margin:0 auto">

  <div style="margin-bottom:28px">
    <h1 style="font-family:'Sora',sans-serif;font-size:1.5rem;font-weight:800;margin:0">Mentor Upgrade Assessment</h1>
    <p style="color:var(--text-3);font-size:0.88rem;margin:6px 0 0">
      Step 1 of 3 — Prove your subject knowledge before your mentor writes your recommendation.
    </p>
  </div>

  {{-- Step indicator --}}
  <div style="display:flex;align-items:center;gap:0;margin-bottom:28px">
    @foreach([['1','Assessment','active'],['2','Recommendation',''],['3','Admin Approval','']] as [$n,$label,$state])
    <div style="display:flex;align-items:center;flex:1">
      <div style="display:flex;flex-direction:column;align-items:center;gap:4px;flex:1">
        <div style="width:32px;height:32px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:0.82rem;
          {{ $state === 'active' ? 'background:var(--blue-500);color:#fff' : 'background:var(--surface-2);color:var(--text-3);border:2px solid var(--border)' }}">
          {{ $n }}
        </div>
        <div style="font-size:0.72rem;font-weight:600;color:{{ $state === 'active' ? 'var(--blue-500)' : 'var(--text-3)' }}">{{ $label }}</div>
      </div>
      @if(!$loop->last)
      <div style="height:2px;flex:1;background:var(--border);margin-bottom:20px"></div>
      @endif
    </div>
    @endforeach
  </div>

  {{-- Stats --}}
  <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:24px">
    <div class="stat-card">
      <div class="stat-value">{{ $assessment?->questions_per_attempt ?? 15 }}</div>
      <div class="stat-label">Questions</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">
        @php $total = ($assessment?->time_per_question ?? 90) * ($assessment?->questions_per_attempt ?? 15); @endphp
        {{ floor($total/60) }}m {{ $total % 60 > 0 ? ($total % 60).'s' : '' }}
      </div>
      <div class="stat-label">Total Time</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">{{ $assessment?->passing_score ?? 70 }}%</div>
      <div class="stat-label">Pass Mark</div>
    </div>
  </div>

  {{-- Rules --}}
  <div class="card" style="margin-bottom:24px;border-left:4px solid var(--blue-500)">
    <div style="font-family:'Sora',sans-serif;font-weight:700;font-size:1rem;margin-bottom:14px">📋 Assessment Rules</div>
    <ul style="list-style:none;padding:0;margin:0;display:flex;flex-direction:column;gap:10px">
      @foreach([
        ['🎲', 'Questions are randomly selected from a pool — each attempt is unique.'],
        ['↔️', 'You can navigate freely between questions and change answers before submitting.'],
        ['⏱️', 'There is a single total timer for the whole exam. Unanswered questions are marked wrong.'],
        ['👁️', 'Tab switching is monitored. Two switches will auto-submit your test.'],
        ['🔁', 'Maximum 3 attempts. A 24-hour cooldown applies after each failure.'],
        ['✅', 'Score '.($assessment?->passing_score ?? 70).'% or above to unlock the recommendation stage.'],
      ] as [$icon, $text])
      <li style="display:flex;align-items:flex-start;gap:10px;font-size:0.85rem">
        <span style="font-size:1.05rem;flex-shrink:0">{{ $icon }}</span>
        <span style="color:var(--text-2)">{{ $text }}</span>
      </li>
      @endforeach
    </ul>
  </div>

  {{-- Attempt history --}}
  @if($attemptCount > 0)
  <div class="card" style="margin-bottom:24px">
    <div style="font-size:0.85rem;font-weight:700;margin-bottom:6px">Previous Attempts</div>
    <div style="font-size:0.83rem;color:var(--text-3)">
      You have used <strong>{{ $attemptCount }}</strong> of 3 attempts.
      @if($attemptCount >= 3)<span style="color:#dc2626;font-weight:600"> — Maximum attempts reached.</span>@endif
    </div>
  </div>
  @endif

  {{-- CTA --}}
  @if(!$assessment || !$assessment->questions_ready)
    <div style="background:#fef3c7;border:1px solid #fde68a;border-radius:16px;padding:24px;text-align:center">
      <div style="font-size:2rem;margin-bottom:8px">⏳</div>
      <div style="font-weight:700;margin-bottom:6px">Questions Being Prepared</div>
      <p style="font-size:0.85rem;color:var(--text-3);margin:0 0 16px">
        Your assessment questions are being generated by AI based on your completed learning paths.
        This can take up to a minute. Click the button below to generate them now.
      </p>
      <form method="POST" action="{{ route('upgrade-assessment.retryGenerate', $upgradeRequest) }}">
        @csrf
        <button type="submit" class="btn btn-primary">Generate Questions Now</button>
      </form>
    </div>

  @elseif($attemptCount >= 3)
    <div style="background:#fee2e2;border:1px solid #fca5a5;border-radius:16px;padding:20px 24px;text-align:center">
      <div style="font-size:2rem;margin-bottom:8px">🚫</div>
      <div style="font-weight:700;margin-bottom:6px">Maximum Attempts Reached</div>
      <p style="font-size:0.85rem;color:var(--text-3);margin:0">
        You have used all 3 attempts. Please speak with your mentor for guidance.
      </p>
    </div>

  @elseif($cooldownActive)
    <div style="background:#fef3c7;border:1px solid #fde68a;border-radius:16px;padding:20px 24px;text-align:center">
      <div style="font-size:2rem;margin-bottom:8px">⏰</div>
      <div style="font-weight:700;margin-bottom:6px">Cooldown Period Active</div>
      <p style="font-size:0.85rem;color:var(--text-3);margin:0">
        You can retry after <strong>{{ $cooldownEndsAt->format('D, d M Y \a\t g:i A') }}</strong>.
      </p>
      <div id="cdTimer" style="font-family:'Sora',sans-serif;font-weight:800;font-size:1.6rem;color:var(--blue-500);margin-top:12px"></div>
    </div>

  @else
    <div class="card" style="text-align:center;padding:32px">
      <div style="font-size:3rem;margin-bottom:12px">🧠</div>
      <div style="font-family:'Sora',sans-serif;font-weight:800;font-size:1.15rem;margin-bottom:8px">Ready to Prove Your Knowledge?</div>
      <p style="font-size:0.85rem;color:var(--text-3);margin:0 0 24px">
        Once you start, the timer begins immediately. Find a quiet place and focus — you can navigate back and forth between questions freely.
      </p>
      <form method="POST" action="{{ route('upgrade-assessment.start', $upgradeRequest) }}"
            data-confirm="Start the assessment now? The timer will begin immediately.">
        @csrf
        <button type="submit" class="btn btn-primary" style="padding:14px 40px;font-size:1rem">
          🚀 Start Assessment
        </button>
      </form>
      <p style="font-size:0.78rem;color:var(--text-3);margin-top:12px">Attempt {{ $attemptCount + 1 }} of 3</p>
    </div>
  @endif

</div>
@endsection

@push('scripts')
@if($cooldownActive && $cooldownEndsAt)
<script>
(function(){
  const end = new Date('{{ $cooldownEndsAt->toISOString() }}').getTime();
  const el  = document.getElementById('cdTimer');
  function tick(){
    const diff = end - Date.now();
    if (diff <= 0){ el.textContent = 'Ready to retry!'; location.reload(); return; }
    const h = Math.floor(diff/3600000);
    const m = Math.floor((diff%3600000)/60000);
    const s = Math.floor((diff%60000)/1000);
    el.textContent = `${h}h ${m}m ${s}s remaining`;
  }
  tick();
  setInterval(tick, 1000);
})();
</script>
@endif
@endpush
