@extends('layouts.sidebar')
@section('title', 'Take Assessment')
@section('breadcrumbs')<span style="opacity:0.5">›</span> <a href="{{ route('learning.index') }}" style="color:var(--blue-500);text-decoration:none">Learning Paths</a> <span style="opacity:0.5">›</span> <span>Assessment</span>@endsection

@section('page-content')
<div style="max-width:680px;margin:0 auto">

  <div style="margin-bottom:28px">
    <h1 style="font-family:'Sora',sans-serif;font-size:1.5rem;font-weight:800;margin:0">End-of-Path Assessment</h1>
    <p style="color:var(--text-3);font-size:0.88rem;margin:6px 0 0">
      Learning Path: <strong>{{ $certRequest->learningPath->title }}</strong>
    </p>
  </div>

  {{-- Status cards --}}
  <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:24px">
    <div class="stat-card">
      <div class="stat-value">{{ $assessment?->questions_per_attempt ?? 15 }}</div>
      <div class="stat-label">Questions</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">{{ $assessment?->time_per_question ?? 90 }}s</div>
      <div class="stat-label">Per Question</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">{{ $assessment?->passing_score ?? 70 }}%</div>
      <div class="stat-label">Pass Mark</div>
    </div>
  </div>

  {{-- Rules card --}}
  <div class="card" style="margin-bottom:24px;border-left:4px solid var(--blue-500)">
    <div style="font-family:'Sora',sans-serif;font-weight:700;font-size:1rem;margin-bottom:14px"> Before You Begin</div>
    <ul style="list-style:none;padding:0;margin:0;display:flex;flex-direction:column;gap:10px">
      @foreach([
        ['', 'Questions are randomly selected — each attempt is different.'],
        ['', 'Each question has a '.(($assessment?->time_per_question ?? 90)).'‑second timer. Unanswered questions are marked wrong.'],
        ['', 'You cannot go back to a previous question once answered.'],
        ['', 'Tab switching is monitored. Two switches will auto-submit your test.'],
        ['', 'Maximum 3 attempts. A 24-hour cooldown applies after each failure.'],
        ['', 'Score '.(($assessment?->passing_score ?? 70)).'% or above to pass and advance to verifier review.'],
      ] as [$icon, $text])
      <li style="display:flex;align-items:flex-start;gap:10px;font-size:0.85rem">
        <span style="font-size:1.05rem;flex-shrink:0">{{ $icon }}</span>
        <span style="color:var(--text-2)">{{ $text }}</span>
      </li>
      @endforeach
    </ul>
  </div>

  {{-- Attempt history --}}
  @if($attemptCount > 0)
  <div class="card" style="margin-bottom:24px">
    <div style="font-size:0.85rem;font-weight:700;margin-bottom:8px">Previous Attempts</div>
    <div style="font-size:0.83rem;color:var(--text-3)">
      You have used <strong>{{ $attemptCount }}</strong> of 3 attempts.
      @if($attemptCount >= 3)
        <span style="color:#dc2626;font-weight:600"> — Maximum attempts reached.</span>
      @endif
    </div>
  </div>
  @endif

  {{-- Action --}}
  @if(!$assessment || !$assessment->questions_ready)
    <div style="background:#fef3c7;border:1px solid #fde68a;border-radius:16px;padding:20px 24px;text-align:center">
      <div style="font-size:2rem;margin-bottom:8px"></div>
      <div style="font-weight:700;margin-bottom:6px">Questions Being Prepared</div>
      <p style="font-size:0.85rem;color:var(--text-3);margin:0">
        Your assessment questions are being generated by AI. This usually takes under a minute.
        Please refresh this page or check back shortly.
      </p>
    </div>

  @elseif($attemptCount >= 3)
    <div style="background:#fee2e2;border:1px solid #fca5a5;border-radius:16px;padding:20px 24px;text-align:center">
      <div style="font-size:2rem;margin-bottom:8px"></div>
      <div style="font-weight:700;margin-bottom:6px">Maximum Attempts Reached</div>
      <p style="font-size:0.85rem;color:var(--text-3);margin:0">
        You have used all 3 attempts. Please speak with your mentor for guidance before requesting a re-assessment.
      </p>
    </div>

  @elseif($cooldownActive)
    <div style="background:#fef3c7;border:1px solid #fde68a;border-radius:16px;padding:20px 24px;text-align:center">
      <div style="font-size:2rem;margin-bottom:8px"></div>
      <div style="font-weight:700;margin-bottom:6px">Cooldown Period Active</div>
      <p style="font-size:0.85rem;color:var(--text-3);margin:0">
        You can retry after <strong>{{ $cooldownEndsAt->format('D, d M Y \a\t g:i A') }}</strong>.
      </p>
      <div id="cdTimer" style="font-family:'Sora',sans-serif;font-weight:800;font-size:1.6rem;color:var(--blue-500);margin-top:12px"></div>
    </div>

  @else
    <div class="card" style="text-align:center;padding:32px">
      <div style="font-size:3rem;margin-bottom:12px"></div>
      <div style="font-family:'Sora',sans-serif;font-weight:800;font-size:1.15rem;margin-bottom:8px">Ready to Take the Assessment?</div>
      <p style="font-size:0.85rem;color:var(--text-3);margin:0 0 24px">
        Once you start, the timer begins immediately. Make sure you are in a quiet environment.
      </p>
      <form method="POST" action="{{ route('assessment.start', $certRequest) }}"
            data-confirm="Start the assessment now? The timer will begin immediately and you cannot pause.">
        @csrf
        <button type="submit" class="btn btn-primary" style="padding:14px 40px;font-size:1rem">
           Start Assessment
        </button>
      </form>
      <p style="font-size:0.78rem;color:var(--text-3);margin-top:12px">Attempt {{ $attemptCount + 1 }} of 3</p>
    </div>
  @endif

</div>
@endsection

@push('scripts')
@if($cooldownActive && $cooldownEndsAt)
<script>
(function(){
  const end = new Date('{{ $cooldownEndsAt->toISOString() }}').getTime();
  const el  = document.getElementById('cdTimer');
  function tick(){
    const diff = end - Date.now();
    if (diff <= 0){ el.textContent = 'Ready to retry!'; location.reload(); return; }
    const h = Math.floor(diff/3600000);
    const m = Math.floor((diff%3600000)/60000);
    const s = Math.floor((diff%60000)/1000);
    el.textContent = `${h}h ${m}m ${s}s remaining`;
  }
  tick();
  setInterval(tick, 1000);
})();
</script>
@endif
@endpush
